// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package topic

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.ClusterARN, b.ko.Spec.ClusterARN) {
		delta.Add("Spec.ClusterARN", a.ko.Spec.ClusterARN, b.ko.Spec.ClusterARN)
	} else if a.ko.Spec.ClusterARN != nil && b.ko.Spec.ClusterARN != nil {
		if *a.ko.Spec.ClusterARN != *b.ko.Spec.ClusterARN {
			delta.Add("Spec.ClusterARN", a.ko.Spec.ClusterARN, b.ko.Spec.ClusterARN)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.ClusterRef, b.ko.Spec.ClusterRef) {
		delta.Add("Spec.ClusterRef", a.ko.Spec.ClusterRef, b.ko.Spec.ClusterRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.PartitionCount, b.ko.Spec.PartitionCount) {
		delta.Add("Spec.PartitionCount", a.ko.Spec.PartitionCount, b.ko.Spec.PartitionCount)
	} else if a.ko.Spec.PartitionCount != nil && b.ko.Spec.PartitionCount != nil {
		if *a.ko.Spec.PartitionCount != *b.ko.Spec.PartitionCount {
			delta.Add("Spec.PartitionCount", a.ko.Spec.PartitionCount, b.ko.Spec.PartitionCount)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ReplicationFactor, b.ko.Spec.ReplicationFactor) {
		delta.Add("Spec.ReplicationFactor", a.ko.Spec.ReplicationFactor, b.ko.Spec.ReplicationFactor)
	} else if a.ko.Spec.ReplicationFactor != nil && b.ko.Spec.ReplicationFactor != nil {
		if *a.ko.Spec.ReplicationFactor != *b.ko.Spec.ReplicationFactor {
			delta.Add("Spec.ReplicationFactor", a.ko.Spec.ReplicationFactor, b.ko.Spec.ReplicationFactor)
		}
	}

	customPostCompare(delta, a, b)
	return delta
}
